services:
  consul:
    image: hashicorp/consul:latest
    ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  frontend-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=frontend
    - PROXY_HOST=0.0.0.0:5000
    - PROXY_TARGET=http://frontend-instrumented:5000
    ports:
    - 5000:5000
    hostname: frontend
  frontend-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=frontend
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: frontend
    depends_on:
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: frontend-instrumented
  profile-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=profile
    - PROXY_HOST=0.0.0.0:8081
    - PROXY_TARGET=http://profile-instrumented:8081
    hostname: profile
  profile-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=profile
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: profile
    depends_on:
    - mongodb-profile
    - memcached-profile
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: profile-instrumented
  search-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=search
    - PROXY_HOST=0.0.0.0:8082
    - PROXY_TARGET=http://search-instrumented:8082
    hostname: search
  search-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=search
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: search
    depends_on:
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: search-instrumented
  geo-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=geo
    - PROXY_HOST=0.0.0.0:8083
    - PROXY_TARGET=http://geo-instrumented:8083
    hostname: geo
  geo-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=geo
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: geo
    depends_on:
    - mongodb-geo
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: geo-instrumented
  rate-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=rate
    - PROXY_HOST=0.0.0.0:8084
    - PROXY_TARGET=http://rate-instrumented:8084
    hostname: rate
  rate-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=rate
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: rate
    depends_on:
    - mongodb-rate
    - memcached-rate
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: rate-instrumented
  review-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=review
    - PROXY_HOST=0.0.0.0:8088
    - PROXY_TARGET=http://review-instrumented:8088
    hostname: review
  review-instrumented:
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - MEMC_TIMEOUT
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=review
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    entrypoint: review
    container_name: hotel_reserv_review
    depends_on:
    - mongodb-review
    - memcached-review
    - consul
    restart: always
    hostname: review-instrumented
  attractions-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=attractions
    - PROXY_HOST=0.0.0.0:8089
    - PROXY_TARGET=http://attractions-instrumented:8089
    hostname: attractions
  attractions-instrumented:
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - MEMC_TIMEOUT
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=attractions
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    entrypoint: attractions
    container_name: hotel_reserv_attractions
    depends_on:
    - mongodb-attractions
    - consul
    restart: always
    hostname: attractions-instrumented
  recommendation-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=recommendation
    - PROXY_HOST=0.0.0.0:8085
    - PROXY_TARGET=http://recommendation-instrumented:8085
    hostname: recommendation
  recommendation-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=recommendation
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: recommendation
    depends_on:
    - mongodb-recommendation
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: recommendation-instrumented
  user-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=user
    - PROXY_HOST=0.0.0.0:8086
    - PROXY_TARGET=http://user-instrumented:8086
    hostname: user
  user-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=user
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: user
    depends_on:
    - mongodb-user
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: user-instrumented
  reservation-proxy:
    image: ${PROXY_IMAGE:-dflipse/reynard-proxy:latest}
    environment:
    - CONTROLLER_HOST=reynard-controller:5000
    - CONTROL_PORT=5115
    - LOG_LEVEL
    - SERVICE_NAME=reservation
    - PROXY_HOST=0.0.0.0:8087
    - PROXY_TARGET=http://reservation-instrumented:8087
    hostname: reservation
  reservation-instrumented:
    configs:
    - source: server_config
      target: /config.json
    environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
    - OTEL_SERVICE_NAME=reservation
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://reynard-jaeger:4317
    - OTEL_LOGS_EXPORTER=none
    - OTEL_METRICS_EXPORTER=none
    build: .
    image: deathstarbench/hotel-reservation:latest
    entrypoint: reservation
    depends_on:
    - mongodb-reservation
    - memcached-reserve
    - consul
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    hostname: reservation-instrumented
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
    - 16686:16686
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  memcached-rate:
    image: memcached:latest
    hostname: user-memcached
    environment:
    - MEMCACHED_CACHE_SIZE=128
    - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  memcached-review:
    image: memcached
    container_name: hotel_reserv_review_mmc
    restart: always
    environment:
    - MEMCACHED_CACHE_SIZE=128
    - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
  memcached-profile:
    image: memcached:latest
    hostname: user-memcached
    environment:
    - MEMCACHED_CACHE_SIZE=128
    - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  memcached-reserve:
    image: memcached:latest
    hostname: user-memcached
    environment:
    - MEMCACHED_CACHE_SIZE=128
    - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-geo:
    image: mongo:5.0
    hostname: geo-db
    volumes:
    - geo:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-profile:
    image: mongo:5.0
    hostname: profile-db
    volumes:
    - profile:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-rate:
    image: mongo:5.0
    hostname: rate-db
    volumes:
    - rate:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-review:
    image: mongo:5.0
    hostname: review-db
    volumes:
    - review:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-attractions:
    image: mongo:5.0
    hostname: attractions-db
    volumes:
    - attractions:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-recommendation:
    image: mongo:5.0
    hostname: recommendation-db
    volumes:
    - recommendation:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-reservation:
    image: mongo:5.0
    hostname: reservation-db
    volumes:
    - reservation:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  mongodb-user:
    image: mongo:5.0
    hostname: user-db
    volumes:
    - user:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  reynard-jaeger:
    image: jaegertracing/jaeger:latest
    ports:
    - 16687:16686
    environment:
    - COLLECTOR_OTLP_ENABLED=true
  reynard-controller:
    image: ${CONTROLLER_IMAGE:-dflipse/reynard-controller:latest}
    ports:
    - 6116:5000
    environment:
    - PROXY_LIST=frontend:5115,profile:5115,search:5115,geo:5115,rate:5115,review:5115,attractions:5115,recommendation:5115,user:5115,reservation:5115
    - LOG_LEVEL
version: '3.8'
volumes:
  geo: null
  profile: null
  rate: null
  recommendation: null
  reservation: null
  user: null
  review: null
  attractions: null
configs:
  server_config:
    file: ./config.json
